---
- hosts: all
  sudo: yes
  tasks:
    - name: Install docker
      yum: name=https://get.docker.com/rpm/1.7.0/centos-7/RPMS/x86_64/docker-engine-1.7.0-1.el7.centos.x86_64.rpm state=present

    - name: Ensure docker is running always
      service: name=docker enabled=yes state=started
